# Cloudflare Pages 配置文件（可选）
# 使用 wrangler CLI 部署时会用到

name = "short-tv-ui"
compatibility_date = "2024-01-01"

# Pages 项目配置
pages_build_output_dir = "dist"

# 环境变量（如果需要）
# [env.production.vars]
# API_URL = "https://api.example.com"
